theme: jekyll-theme-Hacker
show_downloads: true
github:
  apple_url: https://github.com/rageworx/FLTermEx/releases/download/v2.2.1.8/FLTermEx-macOS11-aarch64-v2.2.1.8.zip
  zip_url: https://github.com/rageworx/FLTermEx/releases/download/v2.2.1.8/FLTermEx_Win32_x86_64_v2.2.1.8_selfsigned.zip
  description: fast light terminal extra fatured emulator
